[project]
name = "biud"
description = ""
authors = []

[contracts.biud-username]
path = "contracts/biud-username-v4.clar"
clarity_version = 2
epoch = 2.5

[contracts.biud-resolver]
path = "contracts/biud-resolver-v2.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]
