[network]
name = "mainnet"
stacks_node_rpc_url = "https://stacks-node-api.mainnet.stacks.co"

[accounts.deployer]
mnemonic = "soap when truly spring audit wait country smooth essence cradle chuckle twenty"
